### ISSUE TITLE
Raw results from "An Empirical Evaluation of Early Time-Series Classification Algorithms"

### ISSUE THREAD

**Issue by JakubBilski** [Eukla/ETS#1]
Hello, thank you for amazing work. Do you plan to upload raw results of experiments you've described in the paper?
Also, do you plan to expand the benchmark to incorporate new methods? Together with my supervisor, I've recently created a new method that outperforms the current methods on most of the data sets. Would you be interested in merging my pull request if I created one?

**Comment by xarakas** [comment]
Dear @JakubBilski, 

the repo is further maintained via this fork:
https://github.com/xarakas/ETSC
where we are expanding the framework with more methods.
Also, the results of an extended experimental evaluation will be uploaded there promptly.

Feel free to create a pull request there.

Thanks!
